### ISSUE TITLE
#67 build crash

### ISSUE THREAD

**Issue by MixSt** [GTNewHorizons/GT5-Unofficial#21]
Client/server crashes with java.lang.NoSuchFieldError: Voidmetal 
http://pastebin.com/RajERf1V
65-th build works fine

**Comment by Dream-Master** [comment]
Use newer Core Mod Version because I change the name.

http://jenkins.usrv.de:8081/job/GTNewHorizons-Core-Mod/

Build on Jenkins are Test Build so better use some recommended versions including in my Modpack pack.

**Comment by Dream-Master** [comment]
If you add custom Mods to the Pack this could work but not always and I can not give any Guaranties.

**Comment by MixSt** [comment]
> I can not give any Guaranties

I understand. Thank you.

**Comment by MixSt** [comment]
@Dream-Master same issue on  GTNewHorizons-Core-Mod 43-th build :( 
http://pastebin.com/GtdjDy9u

**Comment by Technus** [comment]
It is not recommended to update our mods one at a time since lot of the Code interloops with other mods that we edit and that might cause uncompatibilities.
It is recommended to use what the technic platform launcher gives you for both server and clients. (if u want to update server files to newest version of the modpack just look at the changelogs, or copy paste things from client and remove client side only mods, recommended to remove the config and scripts before pasting into server).

**Comment by Technus** [comment]
Also if the crash is about mising stuff it is probably because u dont have the proper version of coremod,, our GT builds heavly depend on it.
